export const GET_TAST_REQUEST="GET_TAST_REQUEST";
export const GET_TAST_SUCCESS="GET_TAST_SUCCESS";
export const GET_TAST_FAILUIR="GET_TAST_FAILUIR";


export const POST_TAST_REQUEST="POST_TAST_REQUEST";
export const POST_TAST_SUCCESS="POST_TAST_SUCCESS";
export const POST_TAST_FAILUIR="POST_TAST_FAILUIR";